version: "3.5"

services:
  
  zookeeper:
    image: confluent/zookeeper
    container_name: dev_zookeeper
    network_mode: host    
    ports:
      - "2181:2181"
    environment:
      zk_id: "1"

  kafka:
    image: confluent/kafka
    container_name: dev_kafka
    depends_on:
      - zookeeper
    network_mode: host      
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "localhost:2181"
